@startuml Zustandsdiagramm

[*] --> index
index: cookie

state "/login" as auth {
    Anmeldeformular: username
    Anmeldeformular: password
    state Anmeldergebnis <<choice>>

    [*] --> Anmeldeformular
    Anmeldeformular --> Anmeldergebnis
    Anmeldergebnis --> AnmeldeFehler: Fehlerhafte Daten
    Anmeldergebnis --> BackendFehlerAuth: Backend nicht erreichbar
    Anmeldergebnis --> [*]: Erfolg
}

state "/create" as create {

    state Anlegeergebnis <<choice>>
    Anlegeformular: form
    [*] --> Anlegeformular


    state Anlegeergebnis <<choice>>

    Anlegeformular --> Anlegeergebnis
    Anlegeergebnis --> AnlegeFehler :Fehlerhafte Daten
    Anlegeergebnis --> BackendFehlerCreate: Backend nicht erreichbar
    Anlegeergebnis --> [*]: Erfolg

}

state "/search" as search {
    state Suchergebnis <<choice>>

    [*] --> Suchformular
    Suchformular: suchkriterien
    state Suchergebnis <<choice>>

    Suchformular --> Suchergebnis: false
    Suchergebnis --> KeineBuecher: Keine Bücher
    Suchergebnis --> BackendFehlerSearch: Backend nicht erreichbar
    Suchergebnis --> GefundeneBuecher: >= 1 Buch
}

state "/success" as success {
    Erfolgsmeldung: Meldungstext
}



index --> auth: Button "Login"
auth --> index : Button "Logout"(authorisiert)
index --> create: Menüpunkt "Anlegen" (authorisiert)
index --> search: Menüpunkt "Suche"
create --> success : Erfolgreich angelegt
@enduml
