@startuml Zustandsdiagramm

[*] --> index
index: cookie

state "/login" as auth {
    Anmeldeformular: username
    Anmeldeformular: password
    state Anmeldergebnis <<choice>>

    [*] --> Anmeldeformular
    Anmeldeformular --> Anmeldergebnis
    Anmeldergebnis --> AnmeldeFehler: Fehlerhafte Daten
    Anmeldergebnis --> BackendFehlerAuth: Backend nicht erreichbar
    Anmeldergebnis --> [*]: Erfolg
}

state "/create" as create {
    Anlegeformular: form
    state Anmeldeergebnis <<choice>>

    [*] --> Anlegeformular
    Anlegeformular --> Anmeldeergebnis
    Anmeldeergebnis --> AnlegeFehler: Fehlerhafte Daten
    Anmeldeergebnis --> BackendFehlerCreate: Backend nicht erreichbar
    Anmeldeergebnis --> [*]: Erfolg
}
state "/search" as search {

    state Suchergebnis <<choice>>

    [*] --> Suchformular
     Suchformular: suchkriterien
        LadenRoot: true / false
        state Suchergebnis <<choice>>


        Suchformular --> LadenRoot: Button "Suchen"
        LadenRoot --> Suchergebnis: false
        Suchergebnis --> KeineBuecher: Keine Bücher
        Suchergebnis --> BackendFehlerRoot: Backend nicht erreichbar
        Suchergebnis --> GefundeneBuecher: >= 1 Buch

}



index --> auth: Button "Login"
auth --> index : Button "Logout"
index --> create: Menüpunkt "Anlegen"(authorisiert)
index --> search: Menüpunkt "Suche"
create --> search: erfolgreich angelegt



@enduml